CREATE TABLE WORD_LIST (
	ID								INT4 NOT NULL,
	WORD							VARCHAR(255) NOT NULL,
	IND_FAVORITE			BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (ID)
);

ALTER TABLE WORD_LIST ADD CONSTRAINT CT_WORD_LIST_01 UNIQUE (ID);
CREATE SEQUENCE SEQ_WORD_LIST INCREMENT BY 1 START WITH 1;
