CREATE TABLE CATALOGO_FILMES (
	ID_INTERNO_FILME       		INT4 NOT NULL,
	ID            						TEXT,
	TITLE        							VARCHAR(500) NOT NULL,
	ORIGINAL_TITLE          	VARCHAR(500) NOT NULL,
	ORIGINAL_TITLE_ROMANISED 	VARCHAR(500) NOT NULL,
	IMAGE 										TEXT NOT NULL,
	MOVIE_BANNER 							TEXT NOT NULL,
	DESCRIPTION             	TEXT NOT NULL,
	DIRECTOR                	VARCHAR(500) NOT NULL,
	PRODUCER             			VARCHAR(500) NOT NULL,
	RELEASE_DATE            	VARCHAR(20),
	RUNNING_TIME            	VARCHAR(20),
	RT_SCORE         					VARCHAR(20),
	PEOPLE    								TEXT,
	SPECIES    								TEXT,
	LOCATIONS    							TEXT,
	VEHICLES    							TEXT,
	URL 											VARCHAR(500),
	PRIMARY KEY(ID_INTERNO_FILME)
);

ALTER TABLE CATALOGO_FILMES ADD CONSTRAINT CT_CATALOGO_FILMES_01 UNIQUE (ID);
CREATE SEQUENCE SEQ_CATALOGO_FILMES INCREMENT BY 1 START WITH 1;
